### ISSUE TITLE
Doesn't compile with rust nightly

### ISSUE THREAD

**Issue by tamird** [crabtw/rust-bindgen#184]
Looks like the refactoring in https://github.com/rust-lang/rust/pull/23265 removed some things `rust-bindgen` depends on.

**Comment by jfager** [comment]
@eddyb Would you possibly have some time to help out w/ this?

**Comment by eddyb** [comment]
Sure, ping me on IRC. I can't easily tell what bindgen was using, `quote_method!`?
I recall someone asking about bindgen last week, I thought it was going to be fixed already.

**Comment by tupshin** [comment]
I'm also not sure how to fix the quote_method! uses now that it is gone, and this is blocking me as well.

**Comment by willmtemple** [comment]
There have been other changes as well which affected this repo. I'm not a super-advanced rust programmer by any means, but any attempt on my end thus far to fix it has been a rabbit-hole. Here's what I've done. I was able to at least patch away the error by adding the suggestion of a quote_impl_item! macro to the syntax library, but I have no indication of whether or not it's been done correctly (I've never mucked around at that level in rust) New versions of the compiler have also altered the prelude to remove re-exports of old_io and old_path. That breaks build.rs in this repo. The script is a pretty easy fix, though. After patching that away, there were errors in clang.rs resulting from the public re-export of clangll (I'm not sure why it got angry at this, but removing the re-export and changing all uses of clang::ll:: to clangll:: removed those errors. Finally, there are errors in gen.rs. resulting from mismatched types. It seems like most of the ImplItem code now requires syntax::ptr::P<syntax::ast::ImplItem> rather than just the ImplItem struct. It also appears that ast::MethodImplItem in the ImplItem_ enum now requires two arguments rather than one, which also causes problems.

I use this program for a personal project, so I'm interested in helping out however I can, but I'm in a bit over my head at the point that I've locally forked the standard libraries and am lost in a cyclone of pointers and types that I'm not familiar with.

**Comment by kongfushi** [comment]
rust is changing too fast,maybe rust-bindgen shall base on 1.0.0-alpha until 1.0 is release?

**Comment by eddyb** [comment]
@willmtemple I've already shown two different people [this simple workaround](https://github.com/rust-lang/rust/blob/master/src/test/auxiliary/macro_crate_test.rs#L84-L103), for some reason I expected this to be a done deal days ago.
I would rather not add more `quote_*` macros, they're getting a bit silly.

**Comment by jfager** [comment]
I've taken a short run at the simple workaround and am still running into problems that I haven't had time to work through.  I'm not at a computer now so don't have the new error messages in front of me, but it really doesn't seem to be as straightforward as subbing in from the provided example.  

I, too, am out of my depth with this kind of code at this point, so I either need to defer to someone else for the fix, or find a bigger chunk of free time than I've been able to get so far.  

I'll follow up with a pointer to my wip branch and a better description of the errors I'm seeing, but it will be this evening before I can do that.

**Comment by tamird** [comment]
fixed in https://github.com/crabtw/rust-bindgen/pull/186
