### ISSUE TITLE
Fails to build (I think): CommandLine Error

### ISSUE THREAD

**Issue by bfops** [crabtw/rust-bindgen#206]
The instant I start the build, and until I just kill it (after 10-30 minutes), I get *tons* of errors constantly scrolling by that look like:

    <premain>: CommandLine Error: Option 'disable-block-placement' registered more than once!

Is this expected? Should the build be taking this long? I'm building on `rustc 1.1.0-nightly (435622028 2015-05-04)`

**Comment by bfops** [comment]
Eventually it seems like my CPU usage or RAM maxes out, and I have to hard reset..

**Comment by ebarnard** [comment]
Is this when building bindgen or when building something that uses the bindgen! macro? It looks like another incarnation of #89.

**Comment by bfops** [comment]
This is in building bindgen. If I build with no `LD_PRELOAD`, I get an error telling me `libclang.so` can't be found. When I set `LD_PRELOAD` to point to my `libclang`, this happens during `cargo build`.

**Comment by bfops** [comment]
Hm yeah, I do have two LLVM version installed. I'll try removing one.

**Comment by bfops** [comment]
export LD_PRELOAD=/usr/lib/llvm-3.6/lib/libclang.so && cargo clean && cargo build

       Compiling bindgen v0.14.0 (file:///home/ben/devl/rust-bindgen)
       Compiling term v0.2.7
       Compiling bitflags v0.1.1
       Compiling libc v0.1.6
       Compiling rustc-serialize v0.3.14
       Compiling unicode-xid v0.0.1
    <premain>: CommandLine Error: Option 'info-output-file' registered more than once!
    <premain>: CommandLine Error: Option 'track-memory' registered more than once!
    <premain>: CommandLine Error: Option 'stats' registered more than once!
    <premain>: CommandLine Error: Option 'rng-seed' registered more than once!
    <premain>: CommandLine Error: Option 'view-background' registered more than once!

    $ dpkg --get-selections | grep -v deinstall | grep llvm
    libllvm3.6:amd64				install
    libllvm3.6:i386					install
    llvm-3.6					install
    llvm-3.6-dev					install
    llvm-3.6-runtime				install

**Comment by bfops** [comment]
#89 seems to imply I have to build my own LLVM to get bindgen to work. Am I reading that right?

**Comment by ebarnard** [comment]
`LD_PRELOAD` should only be used when you're compiling something which uses the `bindgen!` macro and bindgen is dynamically linked with clang. It is only guaranteed to work if your clang/llvm version is the same as that used by rust, which in your case it isn't.

When compiling bindgen you just need to set `LIBCLANG_PATH` which in your case should be `/usr/lib/llvm-3.6/lib`. If you're planning on using the `bindgen!` macro rather than the command line tool or a `build.rs` script then it's recommended to pass `--features static` to cargo which will link bindgen statically with clang and avoid #89 altogether.

Also you may have to set `LD_LIBRARY_PATH` when running bindgen.

**Comment by bfops** [comment]
Ah, clearly I didn't read closely enough. It seems to work now, thanks!
