### ISSUE TITLE
Support for preprocessor defined constants

### ISSUE THREAD

**Issue by tfar** [crabtw/rust-bindgen#56]
Would it be possible to add support for preprocessor defined constants? To not introduce too much pollution maybe restricted via pattern matching. 

For example for this code:
```
#define BN_POS		(0)

#define BN_NEG		(1)
```
It would be nice to have those constants easily available in the Rust binding.

**Comment by robertknight** [comment]
I started work on a [library](https://github.com/robertknight/cmacros) to parse #defines from C headers and assist with translation to Rust headers.

The approach I've taken is to automate translation of simple macros like the one in the example (simple constants, simple expressions involving constants or other simple macros) and the user can provide a translation function that can skip anything more complex.

This could be used to load the C include from the system and extract the constants for the current platform in build.rs. It won't help if the C code differs per-platform however.

Right now I'm not doing any kind of translation of expressions for cases where C / Rust syntax differs eg. for things like `#define FOO type(constant)`. That is where clang would be useful. Alternatively it might be possible to get quite far with a simple expression parser.

**Comment by luser** [comment]
I have a change to add partial support for generating consts from preprocessor defines:
https://github.com/luser/rust-bindgen/commit/b40fa57910a2851b78a9d1eaaa03c1421abb9a2a

It's limited to only supporting macros that are defined to simple integer literals right now, since it gets really complicated otherwise. Unfortunately it doesn't work with the example given in the initial comment here because of the parens. :-/

**Comment by nox** [comment]
I'll look into it.

**Comment by jethrogb** [comment]
+1

**Comment by jethrogb** [comment]
I'd really like to have this, but I'd want to support any kind of literal: strings, chars, perhaps even initializer lists.
